BEGIN;

CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  phone_number VARCHAR(16) UNIQUE NOT NULL,
  username TEXT UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT 'now()'::TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  updated_at TIMESTAMP DEFAULT 'now()'::TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  deleted_at TIMESTAMP
);

COMMIT;
